export const ROUTES = {
  HOME: "/",
  ARTICLE: "/articles/:username/:articleSlug",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  LOGOUT: "/auth/register",
  AUTHOR: "/authors/:authorId",
  USER_NOTIFICATIONS: "/my-notifications",
  CREATE_ARTICLE: "/create-article",
  USER_PROFILE: "/my-profile",
  USER_PROFILE_DETAILS: "/my-profile/details",
  USER_PROFILE_PREFERENCES: "/my-profile/preferences",
  USER_PROFILE_USER_ARTICLES: "/my-profile/my-articles",
  USER_PROFILE_SAVED_ARTICLES: "/my-profile/saved-articles",
};
